# default config
data:
  format: "volumetric_video"
  data_dir: "scenes/coffee"
  frame_total: 10
  resolution: 2
  # image cached in the memory
  max_cached_img: 100
  # point cloud init
  init_type: "sfm"
  init_random_num: 10000
  init_random_extend: 3

model:
  # anchor embedding
  anchor_num: 40000
  anchor_feature_dim: 32
  anchor_child_num: 5
  # frame embedding
  frame_start: 0
  frame_end: 1
  frame_dim: 200
  # neural GS MLP
  hidden_dim: 32
  rotate6: False
  trim_by_opacity: True
  view_dependent: False
train:
  # logging
  random_seed: 103
  root: "output/coffee"
  # training
  max_step: 30000
  batch_size: 1
  # [legacy] 
  # init_opacity: 0.1
  # init_scale: 1.0
  # sh_degree: 3
  # sh_degree_interval: 1000
  # lr_mean: 1e-4
  # lr_scale: 5e-3
  # lr_opacity: 5e-2
  # lr_quat: 1e-3
  # lr_sh0: 2.5e-3
  # lr_shN: 1.25e-4
  # [anchor] learning rate
  lr_frame_embed: 0.0075
  lr_anchor_embed: 0.0075
  lr_anchor_xyz: 
    - 1e-4
    - 1e-6
  lr_anchor_offsets: 
    - 1e-2
    - 1e-4
  lr_anchor_offset_extend: 7e-3
  lr_anchor_scale_extend: 7e-3
  lr_anchor_opacity_decay: 1e-5
  # [neural GS] learning rate
  lr_mlp_scales: 0.004
  lr_mlp_quats: 0.004
  lr_mlp_opacities:
    - 2e-3
    - 2e-5
  lr_mlp_colors: 
    - 8e-3
    - 5e-5
  # loss and regularization
  ssim_lambda: 0.2
  reg_opacity: 1e-2
  reg_scale: 0
  reg_volume: 1e-1
  # densification with MCMC relocation
  growing_rate: 0.05
  perturb_intensity: 0
  reloc_start_iter: 500
  reloc_stop_iter: 25000
  reloc_every: 100
  reloc_dead_thres: 0.01
  scale_decay: 0.95 # an approximate of MCMC rescale after relocation
  # evaluation
  test_every: 25
  test_steps:
    - 1000
    - 2000
    - 3000
    - 4000
    - 5000
    - 6000
    - 7000
    - 8000
    - 9000
    - 10000
    - 11000
    - 12000
    - 13000
    - 14000
    - 15000
    - 16000
    - 17000
    - 18000
    - 19000
    - 20000
    - 21000
    - 22000
    - 23000
    - 24000
    - 25000
    - 26000
    - 27000
    - 28000
    - 29000
    - 30000