# default config
data:
  format: "volumetric_video"
  data_dir: "scenes/cook"
  frame_total: 300
  resolution: 2
  cache_device: "torch" # ["cpu", "gpu", "torch"]
  # self implemented dataloader
  max_cached_img: 1000
  # torch based data loader
  num_workers: 4
  min_iter_per_loader: 100
  # point cloud init
  init_type: "sfm"
  init_random_num: 10000
  init_random_extend: 3

model:
  # anchor embedding
  anchor_num: 60000
  anchor_embed_dim: 64    # trainable embedding
  anchor_feature_dim: 64  # intermidiate feature
  anchor_child_num: 5
  # frame embedding
  frame_start: 0
  frame_end: 300
  frame_embed_dim: 200    # trainable embedding
  frame_embed_entangle_range: 0 # per frame embed is weighted avg of nearby frames 
  # accumulative embedding
  embed_accumulative: False # accumulate frame embedding
  # deform MLP
  deform_hidden_dim: 64
  deform_depth: 8
  deform_skip: 4
  deform_anchor_xyz: True
  deform_child_offsets: True # deform child offsets as well
  deform_child_scales: False
  # neural GS MLP
  spawn_hidden_dim: 64
  spawn_xyz_bypass: False
  filter_by_ops: True
  view_dependent: False
  six_dof_rotate: False

train:
  # logging
  random_seed: 103
  root: "output/cook"
  # training
  # train frame by frame
  incremental_routine: False
  incremental_routine_first_frame: 3000
  incremental_routine_frame: 0
  incremental_routine_mixing: 1000
  max_step: 30000
  batch_size: 4
  # [anchor] learning rate
  lr_frame_embed: 0.0075
  lr_mlp_deform: 
    - 1e-4
    - 1e-6
  lr_anchor_embed: 0.0075
  lr_anchor_xyz: 
    - 1e-3
    - 1e-5
    - 0
    - 40000
  lr_anchor_offsets: 
    - 2e-4
    - 2e-6
    - 0
    - 40000
  lr_anchor_offset_extend: 7e-3
  lr_anchor_scale_extend: 7e-3
  lr_anchor_opacity_decay: 1e-2
  # [neural GS] learning rate
  lr_mlp_scales: 0.004
  lr_mlp_quats: 0.004
  lr_mlp_opacities:
    - 2e-3
    - 2e-5
  lr_mlp_colors: 
    - 8e-3
    - 5e-5
  # loss and regularization
  ssim_lambda: 0.2
  reg_opacity: 1e-3
  reg_scale: 0
  reg_volume: 1e-1
  reg_offset: 1e-2
  # densification with MCMC relocation
  growing_rate: 0.05
  perturb_intensity: 0
  reloc_start_iter: 500
  reloc_stop_iter: 1000000
  reloc_every: 50
  reloc_dead_thres: 0.01
  reloc_dead_spawns: 0
  state_ewma_alpha: 0.9
  grad2d_for_impact: 0.1
  scale_decay: 0.9 # an approximate of MCMC rescale after relocation
  blame_start_iter: 3000
  blame_prepare_iters: 10
  blame_max_gs_per_tile: 1000
  always_compute_blame: True
  # evaluation
  tb_histogram: False
  tb_per_frame_psnr: False
  save_eval_img: False
  save_eval_img_every: 1000
  save_model_onnx: False
  test_every: 25
  test_steps_every: 100
  test_steps:
    - 100
    - 1000
    - 2500
    - 5000
    - 7500
    - 10000
    - 12500
    - 15000
    - 17500
    - 20000
    - 22500
    - 25000
    - 27500
    - 30000
    - 35000
    - 40000
    - 45000
    - 50000