#!/bin/bash

test_dir="test_src"

if [ $# -eq 0 ]; then
    echo "Available tests:"
    for file in "$test_dir"/*.py; do
        if [ -f "$file" ]; then
            filename=$(basename -- "$file")
            echo "  ${filename%.py}"
        fi
    done
    echo "Usage: $0 <test_name>"
    exit 0
fi

if [ -f "$test_dir/$1.py" ]; then
    python "$test_dir/$1.py"
else
    echo "Error: Test file '$test_dir/$1.py' not found."
    exit 1
fi